/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BannerForm: typeof import('./components/BannerForm.vue')['default']
    BannerOffer: typeof import('./components/BannerOffer.vue')['default']
    BannerPresentation: typeof import('./components/BannerPresentation.vue')['default']
    BannerServices: typeof import('./components/BannerServices.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    PresentationBanner: typeof import('./components/PresentationBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
